on: [push]

name: CI

jobs:
  build:
    name: Build hits-rs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache rust assets
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install deps
        run: sudo apt-get install sqlite3 libsqlite3-dev

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.44.1

      - name: Build artifact
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
