on:
  push:
    tags:
      - v*

name: Create Release

jobs:
  build:
    name: Release new version on github and docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create github release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build and upload image
        uses: docker/build-push-action@v1
        with:
          username: neslinesli93
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: neslinesli93/hits-rs
          tags: latest,${{ steps.get_version.outputs.VERSION }}
